### ISSUE TITLE
"Free" license

### ISSUE THREAD

**Issue by lehitoskin** [Tox/Sounds#1]
You should specify what exactly constitutes a "free" license in the README. For instance, create an enumerated list of licenses that are okay or link to a website that does the same. Is CC-BY-ND "free"? What about NC? What exactly makes the license free?

These are important questions.

**Comment by JFreegman** [comment]
We should force one license or have a list of licenses we'll accept.

**Comment by GrayHatter** [comment]
I'm hesitant to agree to a CC licence, they're better than most, but they're not really open; at least if you allow Non-derivatives

**Comment by lehitoskin** [comment]
@GrayHatter CC is basically it for non-code things as far as I know. The thing is that you can't really use a software license for sounds because, well, they're designed for code and not media. CC-BY(-SA) is probably the freest already-existing license not tailored specifically for code.

**Comment by Zer0-One** [comment]
I didn't really want to limit submissions to a single license. I was thinking that any license that permits unrestricted use/modification/redistribution would do fine. It would include permissive licenses that let you close off the material if you want, as well as "freedom-preserving" licenses that make sure your changes remain open.

**Comment by Zer0-One** [comment]
Are there still any concerns about this, or can I close this issue with the understanding that a "free" content license is basically the same as a free software license?

**Comment by lehitoskin** [comment]
I suppose that before it's added to the repository the license is checked to see if it's up to snuff. I think it's fine to close this issue now.
