### ISSUE TITLE
All sounds should be in .wav format

### ISSUE THREAD

**Issue by GrayHatter** [Tox/Sounds#9]
This way I can submodule this repo, and it'll still compile on every system. Otherwise I have to pull these into my repo, convert them to .wav, and then commit them. Or I have to add a dependency for software that will convert these into .wav. Neither option seems like the best way to do it.

http://superuser.com/a/553509

**Comment by RowenStipe** [comment]
I'd have to agree with this idea, for some making a `.wav` is easier than anything else. My own sound pack is only `.flac` since it was the first thing I thought of when I read `lossless format` [in the first commit here](https://github.com/Tox/Sounds/commit/2e9b95df5f9093c2cca7fea14880a25d374f3994#diff-04c6e90faac2675aa89e2176d2eec7d8R23).

**Comment by Zer0-One** [comment]
I guess we could enforce this to make things easier on devs who want to use the sounds. Any objections from anyone before I run with it?

**Comment by alexbakker** [comment]
No objections.

**Comment by LittleVulpix** [comment]
How big will these wav files be? Cause they're uncompressed, after all.

**Comment by RowenStipe** [comment]
@LittleVulpix I converted the largest sound file I had in my Chippy sound pack `./Ringtone/IncommingAudio.flac` and converted it to a WAV. It blew up from 438 KB to 1.3 MB for a 7 second track. Considering the size of hard drives and USB thumb drives I don't see this as too big of an issue to have.

**Comment by LittleVulpix** [comment]
@RowenStipe I suppose that's okay. There will be some "overhead" before the application uses/caches the file in memory, as it will take a moment to load a 1.3MB file from a standard disk, but it will likely not be something that'll cause any grief. It'll probably only really be a problem on busy filesystems where every little bit counts (such as very low budget laptops with either incredibly slow flash-based or low-rpm-disk-based storage, during the post-startup phase of running your operating system) - and even then it shouldn't be a big issue.

Additionally - as a bonus sort of - many archivers have a special algorithm for packing wav-pcm files, so you could probably actually end up with a smaller distributable (though the unpacked thing will take up more space)

**Comment by lehitoskin** [comment]
"Incoming" only has one "m". Also, going from 438 KB to 1.3 MB is BLOAT.

**Comment by GrayHatter** [comment]
@lehitoskin agreed, total BLOAT! But you know what else is bloat? Lossless data, we should just go mono with 8bits and 10kHz. Hey if it's good enough for POTS it's good enough for us right?

This is just a sound repo, meant to be an easy way for anyone who wants to make a tox client, can quickly pull in sounds to use. Sounds made by someone who donated their time to make it easier to get good sounds for tox. That's why .wav is better. Everything can play a wav file, and anything can convert a wav file. The same can't be said about flac. So while if you were saying that 2.7x file size change in a client is too much, I'd agree but this repo is just to share sounds. Sounds that you can then adapt and use in <favorite client>.

**Comment by Zer0-One** [comment]
@GrayHatter in the interests of the Golden Future of Tox™, when there are 100 different sound packs in this repo to choose from, I think we're going to stick with FLAC (for size reasons). What I can do to make it easy for clients that don't support FLAC is automatically push releases from travis or jenkins, where the sounds have all been converted to whatever format clients might need. Sound alright?

**Comment by GrayHatter** [comment]
Not, that still breaks this issue. If you're so concerned about the repo becoming unmanageably large. You should switch to submodules. 

Otherwise, it's your repo man

**Comment by Zer0-One** [comment]
@GrayHatter Well, what does it matter whether you submodule them or not? I'd imagine that as long as you have the media in the appropriate format, things will work just fine.

**Comment by GrayHatter** [comment]
With a submodule for each package, you can then download the sounds repo,
and then ONLY the sounds you want to use. Then file size won't matter.

Unless I missed something. The only argument for flat over wav is that flat
is smaller file sizes. Right?
